# Replace removed code with the following
# replace = ""

# Exclude paths you don't want copied to the generated boilerplate
exclude = []

# The `START` delimiter
start = "//Start"

# The `END` delimiter
end = "//End"

# Path to the source file/directory
src = ".meta/example.rs"

# Path where the scaffolded file/directory will live
dest = "src/lib.rs"

